amce_film:
    resource: "@AmceFilmBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

user:
    resource: "@AcmeUserBundle/Controller/UserController.php"
    type:     annotation

film:
    resource: "@AmceFilmBundle/Controller/FilmController.php"
    type:     annotation

app:
    resource: @AppBundle/Controller/
    type:     annotation
